name: Build docs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Building docs
        run: |
          pip install nox
          nox -s docs_build-3.11

      - uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: docs/build/html
