name: Main CI Actions

on:
  push:
    branches: ['main']
  schedule:
    - cron: 0 0 * * *

jobs:
  quality-checks:
    uses: ./.github/workflows/quality-typing-checks.yaml
  test-run-pinned:
    uses: ./.github/workflows/pinned-tests.yaml
    needs: [quality-checks]
