name: Main CI Actions

on:
  push:
    branches: ['main']

jobs:
  quality-checks:
    uses: ./.github/workflows/quality-typing-checks.yaml
  test-run-pinned:
    uses: ./.github/workflows/pinned-tests.yaml
    needs: [quality-checks]
  docs-build:
    uses: ./.github/workflows/docs-build.yaml
    needs: [test-run-pinned]
